version: "3"

services:
  api:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/opt
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'